# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DEBUG": "00_core.ipynb",
         "extract_field": "00_core.ipynb",
         "read_opf_file": "00_core.ipynb",
         "get_title": "00_core.ipynb",
         "get_author": "00_core.ipynb",
         "get_date": "00_core.ipynb",
         "create_book_title": "00_core.ipynb",
         "get_all_epubs": "00_core.ipynb",
         "generate_epub_name": "00_core.ipynb",
         "move_epub": "00_core.ipynb",
         "move_all_epubs": "00_core.ipynb",
         "main": "01-cli.ipynb"}

modules = ["functions.py",
           "cli.py"]

doc_url = "https://jvhest.github.io/nbdev_test/"

git_url = "https://github.com/jvhest/nbdev_test/tree/master/"

def custom_doc_links(name): return None
