# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01-cli.ipynb (unless otherwise specified).

__all__ = ['main']

# Cell
import os
import click

from .functions import generate_epub_name, move_epub, move_all_epubs


@click.command()
@click.argument("epub")
@click.argument("dest")
def main(epub: str, dest: str):
    if os.path.isdir(dest):
        if os.path.isfile(epub):
            status, new_book_title = move_epub(epub, dest)
            if status:
                print(f"1 epub moved: {new_book_title}")
        elif os.path.isdir(epub):
            move_all_epubs(epub, dest)
        else:
            print(f"invalid source file or directory: {epub}")
    else:
        print(f"invalid destination directory: {dest}")
